### ISSUE TITLE
problem with load_model

### ISSUE THREAD

**Issue by gitjuanfmunoz** [FGpramodgupta/BlinkDetection#1]
hello I am trying to execute the code and I get the following error:

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "BlinkDetectionAPI.py", line 16, in <module>
    from keras.models import load_model
  File "/Users/JuanMunoz/anaconda3/lib/python3.7/site-packages/keras/__init__.py", line 6, in <module>
    'Keras requires TensorFlow 2.2 or higher. '
ImportError: Keras requires TensorFlow 2.2 or higher. Install TensorFlow via `pip install tensorflow`

My configuration is the following:

Keras version: 2.4.3
tensorflow version: 2.3.0

What versions do you recommend?

**Comment by FGpramodgupta** [comment]
I am using Keras version 2.2.4-tf and TensorFlow 2.3

I have also encountered this issue which I have fixed by the following  steps:

pip3 install --upgrade pip
pip3 install --upgrade TensorFlow 

f the above steps don't work try to follow the below steps

pip3 install --upgrade pip
uninstall the NumPy 
pip3 install NumPy

then,

uninstall TensorFlow
pip3 install TensorFlow ==2.3


Hope this will help.

Thanks,
